### ISSUE TITLE
Not PHP 5.3 complient

### ISSUE THREAD

**Issue by jurriaanr** [ruudk/PaymentMultisafepayBundle#2]
There is one statement stopping it from being useable on PHP 5.3. In the class Ruudk\Payment\MultisafepayBundle\Plugin\DefaultPlugin empty() is used in a write context 

    if(empty($purchaseResponse->getRedirectUrl())) {

Line 174

**Comment by ruudk** [comment]
Fixed in https://github.com/ruudk/PaymentMultisafepayBundle/commit/2b22cf8d161210d25ef5bdb3ddc55ddded09e639
